/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * CAPSLink - Plataforma de integração CAPS e INSS
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Listar pacientes
 */
export declare const ListPatientsQueryParams: zod.ZodObject<{
    search: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodEnum<["ativo", "inativo", "em_avaliacao"]>>;
}, "strip", zod.ZodTypeAny, {
    status?: "ativo" | "inativo" | "em_avaliacao" | undefined;
    search?: string | undefined;
}, {
    status?: "ativo" | "inativo" | "em_avaliacao" | undefined;
    search?: string | undefined;
}>;
export declare const ListPatientsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    nome: zod.ZodString;
    cpf: zod.ZodString;
    dataNascimento: zod.ZodOptional<zod.ZodDate>;
    diagnostico: zod.ZodOptional<zod.ZodString>;
    cid: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodEnum<["ativo", "inativo", "em_avaliacao"]>;
    telefone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    responsavelTecnico: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "ativo" | "inativo" | "em_avaliacao";
    id: number;
    nome: string;
    cpf: string;
    createdAt: Date;
    updatedAt: Date;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}, {
    status: "ativo" | "inativo" | "em_avaliacao";
    id: number;
    nome: string;
    cpf: string;
    createdAt: Date;
    updatedAt: Date;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}>;
export declare const ListPatientsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    nome: zod.ZodString;
    cpf: zod.ZodString;
    dataNascimento: zod.ZodOptional<zod.ZodDate>;
    diagnostico: zod.ZodOptional<zod.ZodString>;
    cid: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodEnum<["ativo", "inativo", "em_avaliacao"]>;
    telefone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    responsavelTecnico: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "ativo" | "inativo" | "em_avaliacao";
    id: number;
    nome: string;
    cpf: string;
    createdAt: Date;
    updatedAt: Date;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}, {
    status: "ativo" | "inativo" | "em_avaliacao";
    id: number;
    nome: string;
    cpf: string;
    createdAt: Date;
    updatedAt: Date;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}>, "many">;
/**
 * @summary Criar paciente
 */
export declare const CreatePatientBody: zod.ZodObject<{
    nome: zod.ZodString;
    cpf: zod.ZodString;
    dataNascimento: zod.ZodOptional<zod.ZodDate>;
    diagnostico: zod.ZodOptional<zod.ZodString>;
    cid: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodEnum<["ativo", "inativo", "em_avaliacao"]>;
    telefone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    responsavelTecnico: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "ativo" | "inativo" | "em_avaliacao";
    nome: string;
    cpf: string;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}, {
    status: "ativo" | "inativo" | "em_avaliacao";
    nome: string;
    cpf: string;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}>;
/**
 * @summary Obter paciente por ID
 */
export declare const GetPatientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetPatientResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    nome: zod.ZodString;
    cpf: zod.ZodString;
    dataNascimento: zod.ZodOptional<zod.ZodDate>;
    diagnostico: zod.ZodOptional<zod.ZodString>;
    cid: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodEnum<["ativo", "inativo", "em_avaliacao"]>;
    telefone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    responsavelTecnico: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "ativo" | "inativo" | "em_avaliacao";
    id: number;
    nome: string;
    cpf: string;
    createdAt: Date;
    updatedAt: Date;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}, {
    status: "ativo" | "inativo" | "em_avaliacao";
    id: number;
    nome: string;
    cpf: string;
    createdAt: Date;
    updatedAt: Date;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}>;
/**
 * @summary Atualizar paciente
 */
export declare const UpdatePatientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdatePatientBody: zod.ZodObject<{
    nome: zod.ZodString;
    cpf: zod.ZodString;
    dataNascimento: zod.ZodOptional<zod.ZodDate>;
    diagnostico: zod.ZodOptional<zod.ZodString>;
    cid: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodEnum<["ativo", "inativo", "em_avaliacao"]>;
    telefone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    responsavelTecnico: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "ativo" | "inativo" | "em_avaliacao";
    nome: string;
    cpf: string;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}, {
    status: "ativo" | "inativo" | "em_avaliacao";
    nome: string;
    cpf: string;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}>;
export declare const UpdatePatientResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    nome: zod.ZodString;
    cpf: zod.ZodString;
    dataNascimento: zod.ZodOptional<zod.ZodDate>;
    diagnostico: zod.ZodOptional<zod.ZodString>;
    cid: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodEnum<["ativo", "inativo", "em_avaliacao"]>;
    telefone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    responsavelTecnico: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "ativo" | "inativo" | "em_avaliacao";
    id: number;
    nome: string;
    cpf: string;
    createdAt: Date;
    updatedAt: Date;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}, {
    status: "ativo" | "inativo" | "em_avaliacao";
    id: number;
    nome: string;
    cpf: string;
    createdAt: Date;
    updatedAt: Date;
    dataNascimento?: Date | undefined;
    diagnostico?: string | undefined;
    cid?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    responsavelTecnico?: string | undefined;
}>;
/**
 * @summary Listar relatórios técnicos
 */
export declare const ListReportsQueryParams: zod.ZodObject<{
    patientId: zod.ZodOptional<zod.ZodNumber>;
    status: zod.ZodOptional<zod.ZodEnum<["rascunho", "pendente_revisao", "aprovado", "enviado_inss"]>>;
}, "strip", zod.ZodTypeAny, {
    status?: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss" | undefined;
    patientId?: number | undefined;
}, {
    status?: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss" | undefined;
    patientId?: number | undefined;
}>;
export declare const ListReportsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["laudo_inicial", "acompanhamento", "pericia", "recurso"]>;
    status: zod.ZodEnum<["rascunho", "pendente_revisao", "aprovado", "enviado_inss"]>;
    responsavel: zod.ZodString;
    conteudo: zod.ZodOptional<zod.ZodString>;
    dataEnvio: zod.ZodOptional<zod.ZodDate>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    patientName?: string | undefined;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    patientName?: string | undefined;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}>;
export declare const ListReportsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["laudo_inicial", "acompanhamento", "pericia", "recurso"]>;
    status: zod.ZodEnum<["rascunho", "pendente_revisao", "aprovado", "enviado_inss"]>;
    responsavel: zod.ZodString;
    conteudo: zod.ZodOptional<zod.ZodString>;
    dataEnvio: zod.ZodOptional<zod.ZodDate>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    patientName?: string | undefined;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    patientName?: string | undefined;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}>, "many">;
/**
 * @summary Criar relatório técnico
 */
export declare const CreateReportBody: zod.ZodObject<{
    patientId: zod.ZodNumber;
    tipo: zod.ZodEnum<["laudo_inicial", "acompanhamento", "pericia", "recurso"]>;
    status: zod.ZodEnum<["rascunho", "pendente_revisao", "aprovado", "enviado_inss"]>;
    responsavel: zod.ZodString;
    conteudo: zod.ZodOptional<zod.ZodString>;
    dataEnvio: zod.ZodOptional<zod.ZodDate>;
}, "strip", zod.ZodTypeAny, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}>;
/**
 * @summary Obter relatório por ID
 */
export declare const GetReportParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetReportResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["laudo_inicial", "acompanhamento", "pericia", "recurso"]>;
    status: zod.ZodEnum<["rascunho", "pendente_revisao", "aprovado", "enviado_inss"]>;
    responsavel: zod.ZodString;
    conteudo: zod.ZodOptional<zod.ZodString>;
    dataEnvio: zod.ZodOptional<zod.ZodDate>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    patientName?: string | undefined;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    patientName?: string | undefined;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}>;
/**
 * @summary Atualizar relatório
 */
export declare const UpdateReportParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateReportBody: zod.ZodObject<{
    patientId: zod.ZodNumber;
    tipo: zod.ZodEnum<["laudo_inicial", "acompanhamento", "pericia", "recurso"]>;
    status: zod.ZodEnum<["rascunho", "pendente_revisao", "aprovado", "enviado_inss"]>;
    responsavel: zod.ZodString;
    conteudo: zod.ZodOptional<zod.ZodString>;
    dataEnvio: zod.ZodOptional<zod.ZodDate>;
}, "strip", zod.ZodTypeAny, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}>;
export declare const UpdateReportResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["laudo_inicial", "acompanhamento", "pericia", "recurso"]>;
    status: zod.ZodEnum<["rascunho", "pendente_revisao", "aprovado", "enviado_inss"]>;
    responsavel: zod.ZodString;
    conteudo: zod.ZodOptional<zod.ZodString>;
    dataEnvio: zod.ZodOptional<zod.ZodDate>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    patientName?: string | undefined;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}, {
    status: "rascunho" | "pendente_revisao" | "aprovado" | "enviado_inss";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    tipo: "laudo_inicial" | "acompanhamento" | "pericia" | "recurso";
    responsavel: string;
    patientName?: string | undefined;
    conteudo?: string | undefined;
    dataEnvio?: Date | undefined;
}>;
/**
 * @summary Excluir relatório
 */
export declare const DeleteReportParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Listar processos previdenciários
 */
export declare const ListProcessesQueryParams: zod.ZodObject<{
    patientId: zod.ZodOptional<zod.ZodNumber>;
    status: zod.ZodOptional<zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>>;
}, "strip", zod.ZodTypeAny, {
    status?: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado" | undefined;
    patientId?: number | undefined;
}, {
    status?: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado" | undefined;
    patientId?: number | undefined;
}>;
export declare const ListProcessesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    numeroProcesso: zod.ZodString;
    beneficio: zod.ZodEnum<["bpc_loas", "auxilio_doenca", "aposentadoria_invalidez", "auxilio_acidente"]>;
    status: zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>;
    dataAbertura: zod.ZodDate;
    dataDecisao: zod.ZodOptional<zod.ZodDate>;
    retrabalhos: zod.ZodNumber;
    observacoes: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}>;
export declare const ListProcessesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    numeroProcesso: zod.ZodString;
    beneficio: zod.ZodEnum<["bpc_loas", "auxilio_doenca", "aposentadoria_invalidez", "auxilio_acidente"]>;
    status: zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>;
    dataAbertura: zod.ZodDate;
    dataDecisao: zod.ZodOptional<zod.ZodDate>;
    retrabalhos: zod.ZodNumber;
    observacoes: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}>, "many">;
/**
 * @summary Criar processo previdenciário
 */
export declare const CreateProcessBody: zod.ZodObject<{
    patientId: zod.ZodNumber;
    numeroProcesso: zod.ZodString;
    beneficio: zod.ZodEnum<["bpc_loas", "auxilio_doenca", "aposentadoria_invalidez", "auxilio_acidente"]>;
    status: zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>;
    dataAbertura: zod.ZodDate;
    dataDecisao: zod.ZodOptional<zod.ZodDate>;
    retrabalhos: zod.ZodOptional<zod.ZodNumber>;
    observacoes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    dataDecisao?: Date | undefined;
    retrabalhos?: number | undefined;
    observacoes?: string | undefined;
}, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    dataDecisao?: Date | undefined;
    retrabalhos?: number | undefined;
    observacoes?: string | undefined;
}>;
/**
 * @summary Obter processo por ID
 */
export declare const GetProcessParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetProcessResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    numeroProcesso: zod.ZodString;
    beneficio: zod.ZodEnum<["bpc_loas", "auxilio_doenca", "aposentadoria_invalidez", "auxilio_acidente"]>;
    status: zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>;
    dataAbertura: zod.ZodDate;
    dataDecisao: zod.ZodOptional<zod.ZodDate>;
    retrabalhos: zod.ZodNumber;
    observacoes: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}>;
/**
 * @summary Atualizar processo
 */
export declare const UpdateProcessParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateProcessBody: zod.ZodObject<{
    patientId: zod.ZodNumber;
    numeroProcesso: zod.ZodString;
    beneficio: zod.ZodEnum<["bpc_loas", "auxilio_doenca", "aposentadoria_invalidez", "auxilio_acidente"]>;
    status: zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>;
    dataAbertura: zod.ZodDate;
    dataDecisao: zod.ZodOptional<zod.ZodDate>;
    retrabalhos: zod.ZodOptional<zod.ZodNumber>;
    observacoes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    dataDecisao?: Date | undefined;
    retrabalhos?: number | undefined;
    observacoes?: string | undefined;
}, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    dataDecisao?: Date | undefined;
    retrabalhos?: number | undefined;
    observacoes?: string | undefined;
}>;
export declare const UpdateProcessResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    numeroProcesso: zod.ZodString;
    beneficio: zod.ZodEnum<["bpc_loas", "auxilio_doenca", "aposentadoria_invalidez", "auxilio_acidente"]>;
    status: zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>;
    dataAbertura: zod.ZodDate;
    dataDecisao: zod.ZodOptional<zod.ZodDate>;
    retrabalhos: zod.ZodNumber;
    observacoes: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}>;
/**
 * @summary Processos recentes (feed de atividade)
 */
export declare const listRecentProcessesQueryLimitDefault = 10;
export declare const ListRecentProcessesQueryParams: zod.ZodObject<{
    limit: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit: number;
}, {
    limit?: number | undefined;
}>;
export declare const ListRecentProcessesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    numeroProcesso: zod.ZodString;
    beneficio: zod.ZodEnum<["bpc_loas", "auxilio_doenca", "aposentadoria_invalidez", "auxilio_acidente"]>;
    status: zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>;
    dataAbertura: zod.ZodDate;
    dataDecisao: zod.ZodOptional<zod.ZodDate>;
    retrabalhos: zod.ZodNumber;
    observacoes: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}>;
export declare const ListRecentProcessesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    patientId: zod.ZodNumber;
    patientName: zod.ZodOptional<zod.ZodString>;
    numeroProcesso: zod.ZodString;
    beneficio: zod.ZodEnum<["bpc_loas", "auxilio_doenca", "aposentadoria_invalidez", "auxilio_acidente"]>;
    status: zod.ZodEnum<["em_andamento", "deferido", "indeferido", "recurso", "judicializado"]>;
    dataAbertura: zod.ZodDate;
    dataDecisao: zod.ZodOptional<zod.ZodDate>;
    retrabalhos: zod.ZodNumber;
    observacoes: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}, {
    status: "recurso" | "em_andamento" | "deferido" | "indeferido" | "judicializado";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    patientId: number;
    numeroProcesso: string;
    beneficio: "bpc_loas" | "auxilio_doenca" | "aposentadoria_invalidez" | "auxilio_acidente";
    dataAbertura: Date;
    retrabalhos: number;
    patientName?: string | undefined;
    dataDecisao?: Date | undefined;
    observacoes?: string | undefined;
}>, "many">;
/**
 * @summary Listar treinamentos
 */
export declare const ListTrainingsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    titulo: zod.ZodString;
    descricao: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["plataforma", "documentacao", "previdenciario", "outros"]>;
    modalidade: zod.ZodEnum<["presencial", "online", "hibrido"]>;
    dataRealizacao: zod.ZodDate;
    participantes: zod.ZodNumber;
    status: zod.ZodEnum<["agendado", "em_andamento", "concluido", "cancelado"]>;
    responsavel: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    id: number;
    createdAt: Date;
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    id: number;
    createdAt: Date;
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}>;
export declare const ListTrainingsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    titulo: zod.ZodString;
    descricao: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["plataforma", "documentacao", "previdenciario", "outros"]>;
    modalidade: zod.ZodEnum<["presencial", "online", "hibrido"]>;
    dataRealizacao: zod.ZodDate;
    participantes: zod.ZodNumber;
    status: zod.ZodEnum<["agendado", "em_andamento", "concluido", "cancelado"]>;
    responsavel: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    id: number;
    createdAt: Date;
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    id: number;
    createdAt: Date;
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}>, "many">;
/**
 * @summary Criar treinamento
 */
export declare const CreateTrainingBody: zod.ZodObject<{
    titulo: zod.ZodString;
    descricao: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["plataforma", "documentacao", "previdenciario", "outros"]>;
    modalidade: zod.ZodEnum<["presencial", "online", "hibrido"]>;
    dataRealizacao: zod.ZodDate;
    participantes: zod.ZodNumber;
    status: zod.ZodEnum<["agendado", "em_andamento", "concluido", "cancelado"]>;
    responsavel: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}>;
/**
 * @summary Atualizar treinamento
 */
export declare const UpdateTrainingParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateTrainingBody: zod.ZodObject<{
    titulo: zod.ZodString;
    descricao: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["plataforma", "documentacao", "previdenciario", "outros"]>;
    modalidade: zod.ZodEnum<["presencial", "online", "hibrido"]>;
    dataRealizacao: zod.ZodDate;
    participantes: zod.ZodNumber;
    status: zod.ZodEnum<["agendado", "em_andamento", "concluido", "cancelado"]>;
    responsavel: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}>;
export declare const UpdateTrainingResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    titulo: zod.ZodString;
    descricao: zod.ZodOptional<zod.ZodString>;
    tipo: zod.ZodEnum<["plataforma", "documentacao", "previdenciario", "outros"]>;
    modalidade: zod.ZodEnum<["presencial", "online", "hibrido"]>;
    dataRealizacao: zod.ZodDate;
    participantes: zod.ZodNumber;
    status: zod.ZodEnum<["agendado", "em_andamento", "concluido", "cancelado"]>;
    responsavel: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    id: number;
    createdAt: Date;
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}, {
    status: "em_andamento" | "agendado" | "concluido" | "cancelado";
    id: number;
    createdAt: Date;
    tipo: "plataforma" | "documentacao" | "previdenciario" | "outros";
    responsavel: string;
    titulo: string;
    modalidade: "presencial" | "online" | "hibrido";
    dataRealizacao: Date;
    participantes: number;
    descricao?: string | undefined;
}>;
/**
 * @summary Excluir treinamento
 */
export declare const DeleteTrainingParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Resumo geral do dashboard
 */
export declare const GetDashboardSummaryResponse: zod.ZodObject<{
    totalPacientes: zod.ZodNumber;
    pacientesAtivos: zod.ZodNumber;
    totalProcessos: zod.ZodNumber;
    processosEmAndamento: zod.ZodNumber;
    totalRelatorios: zod.ZodNumber;
    relatoriosPendentes: zod.ZodNumber;
    totalTreinamentos: zod.ZodNumber;
    treinamentosConcluidos: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    totalPacientes: number;
    pacientesAtivos: number;
    totalProcessos: number;
    processosEmAndamento: number;
    totalRelatorios: number;
    relatoriosPendentes: number;
    totalTreinamentos: number;
    treinamentosConcluidos: number;
}, {
    totalPacientes: number;
    pacientesAtivos: number;
    totalProcessos: number;
    processosEmAndamento: number;
    totalRelatorios: number;
    relatoriosPendentes: number;
    totalTreinamentos: number;
    treinamentosConcluidos: number;
}>;
/**
 * @summary Indicadores de desempenho (KPIs)
 */
export declare const GetDashboardKpisResponse: zod.ZodObject<{
    tempoMedioConcessaoDias: zod.ZodNumber;
    taxaIndeferimento: zod.ZodNumber;
    totalRetrabalhos: zod.ZodNumber;
    totalJudicializados: zod.ZodNumber;
    taxaDeferimento: zod.ZodNumber;
    relatoriosAprovadosPct: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    tempoMedioConcessaoDias: number;
    taxaIndeferimento: number;
    totalRetrabalhos: number;
    totalJudicializados: number;
    taxaDeferimento: number;
    relatoriosAprovadosPct: number;
}, {
    tempoMedioConcessaoDias: number;
    taxaIndeferimento: number;
    totalRetrabalhos: number;
    totalJudicializados: number;
    taxaDeferimento: number;
    relatoriosAprovadosPct: number;
}>;
/**
 * @summary Distribuição de processos por status
 */
export declare const GetDashboardProcessStatusResponseItem: zod.ZodObject<{
    status: zod.ZodString;
    count: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    status: string;
    count: number;
}, {
    status: string;
    count: number;
}>;
export declare const GetDashboardProcessStatusResponse: zod.ZodArray<zod.ZodObject<{
    status: zod.ZodString;
    count: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    status: string;
    count: number;
}, {
    status: string;
    count: number;
}>, "many">;
//# sourceMappingURL=api.d.ts.map