/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * CAPSLink - Plataforma de integração CAPS e INSS
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type PatientStatus = (typeof PatientStatus)[keyof typeof PatientStatus];

export const PatientStatus = {
  ativo: "ativo",
  inativo: "inativo",
  em_avaliacao: "em_avaliacao",
} as const;

export interface Patient {
  id: number;
  nome: string;
  cpf: string;
  dataNascimento?: string;
  diagnostico?: string;
  cid?: string;
  status: PatientStatus;
  telefone?: string;
  email?: string;
  responsavelTecnico?: string;
  createdAt: string;
  updatedAt: string;
}

export type CreatePatientBodyStatus =
  (typeof CreatePatientBodyStatus)[keyof typeof CreatePatientBodyStatus];

export const CreatePatientBodyStatus = {
  ativo: "ativo",
  inativo: "inativo",
  em_avaliacao: "em_avaliacao",
} as const;

export interface CreatePatientBody {
  nome: string;
  cpf: string;
  dataNascimento?: string;
  diagnostico?: string;
  cid?: string;
  status: CreatePatientBodyStatus;
  telefone?: string;
  email?: string;
  responsavelTecnico?: string;
}

export type ReportTipo = (typeof ReportTipo)[keyof typeof ReportTipo];

export const ReportTipo = {
  laudo_inicial: "laudo_inicial",
  acompanhamento: "acompanhamento",
  pericia: "pericia",
  recurso: "recurso",
} as const;

export type ReportStatus = (typeof ReportStatus)[keyof typeof ReportStatus];

export const ReportStatus = {
  rascunho: "rascunho",
  pendente_revisao: "pendente_revisao",
  aprovado: "aprovado",
  enviado_inss: "enviado_inss",
} as const;

export interface Report {
  id: number;
  patientId: number;
  patientName?: string;
  tipo: ReportTipo;
  status: ReportStatus;
  responsavel: string;
  conteudo?: string;
  dataEnvio?: string;
  createdAt: string;
  updatedAt: string;
}

export type CreateReportBodyTipo =
  (typeof CreateReportBodyTipo)[keyof typeof CreateReportBodyTipo];

export const CreateReportBodyTipo = {
  laudo_inicial: "laudo_inicial",
  acompanhamento: "acompanhamento",
  pericia: "pericia",
  recurso: "recurso",
} as const;

export type CreateReportBodyStatus =
  (typeof CreateReportBodyStatus)[keyof typeof CreateReportBodyStatus];

export const CreateReportBodyStatus = {
  rascunho: "rascunho",
  pendente_revisao: "pendente_revisao",
  aprovado: "aprovado",
  enviado_inss: "enviado_inss",
} as const;

export interface CreateReportBody {
  patientId: number;
  tipo: CreateReportBodyTipo;
  status: CreateReportBodyStatus;
  responsavel: string;
  conteudo?: string;
  dataEnvio?: string;
}

export type ProcessBeneficio =
  (typeof ProcessBeneficio)[keyof typeof ProcessBeneficio];

export const ProcessBeneficio = {
  bpc_loas: "bpc_loas",
  auxilio_doenca: "auxilio_doenca",
  aposentadoria_invalidez: "aposentadoria_invalidez",
  auxilio_acidente: "auxilio_acidente",
} as const;

export type ProcessStatus = (typeof ProcessStatus)[keyof typeof ProcessStatus];

export const ProcessStatus = {
  em_andamento: "em_andamento",
  deferido: "deferido",
  indeferido: "indeferido",
  recurso: "recurso",
  judicializado: "judicializado",
} as const;

export interface Process {
  id: number;
  patientId: number;
  patientName?: string;
  numeroProcesso: string;
  beneficio: ProcessBeneficio;
  status: ProcessStatus;
  dataAbertura: string;
  dataDecisao?: string;
  retrabalhos: number;
  observacoes?: string;
  createdAt: string;
  updatedAt: string;
}

export type CreateProcessBodyBeneficio =
  (typeof CreateProcessBodyBeneficio)[keyof typeof CreateProcessBodyBeneficio];

export const CreateProcessBodyBeneficio = {
  bpc_loas: "bpc_loas",
  auxilio_doenca: "auxilio_doenca",
  aposentadoria_invalidez: "aposentadoria_invalidez",
  auxilio_acidente: "auxilio_acidente",
} as const;

export type CreateProcessBodyStatus =
  (typeof CreateProcessBodyStatus)[keyof typeof CreateProcessBodyStatus];

export const CreateProcessBodyStatus = {
  em_andamento: "em_andamento",
  deferido: "deferido",
  indeferido: "indeferido",
  recurso: "recurso",
  judicializado: "judicializado",
} as const;

export interface CreateProcessBody {
  patientId: number;
  numeroProcesso: string;
  beneficio: CreateProcessBodyBeneficio;
  status: CreateProcessBodyStatus;
  dataAbertura: string;
  dataDecisao?: string;
  retrabalhos?: number;
  observacoes?: string;
}

export type TrainingTipo = (typeof TrainingTipo)[keyof typeof TrainingTipo];

export const TrainingTipo = {
  plataforma: "plataforma",
  documentacao: "documentacao",
  previdenciario: "previdenciario",
  outros: "outros",
} as const;

export type TrainingModalidade =
  (typeof TrainingModalidade)[keyof typeof TrainingModalidade];

export const TrainingModalidade = {
  presencial: "presencial",
  online: "online",
  hibrido: "hibrido",
} as const;

export type TrainingStatus =
  (typeof TrainingStatus)[keyof typeof TrainingStatus];

export const TrainingStatus = {
  agendado: "agendado",
  em_andamento: "em_andamento",
  concluido: "concluido",
  cancelado: "cancelado",
} as const;

export interface Training {
  id: number;
  titulo: string;
  descricao?: string;
  tipo: TrainingTipo;
  modalidade: TrainingModalidade;
  dataRealizacao: string;
  participantes: number;
  status: TrainingStatus;
  responsavel: string;
  createdAt: string;
}

export type CreateTrainingBodyTipo =
  (typeof CreateTrainingBodyTipo)[keyof typeof CreateTrainingBodyTipo];

export const CreateTrainingBodyTipo = {
  plataforma: "plataforma",
  documentacao: "documentacao",
  previdenciario: "previdenciario",
  outros: "outros",
} as const;

export type CreateTrainingBodyModalidade =
  (typeof CreateTrainingBodyModalidade)[keyof typeof CreateTrainingBodyModalidade];

export const CreateTrainingBodyModalidade = {
  presencial: "presencial",
  online: "online",
  hibrido: "hibrido",
} as const;

export type CreateTrainingBodyStatus =
  (typeof CreateTrainingBodyStatus)[keyof typeof CreateTrainingBodyStatus];

export const CreateTrainingBodyStatus = {
  agendado: "agendado",
  em_andamento: "em_andamento",
  concluido: "concluido",
  cancelado: "cancelado",
} as const;

export interface CreateTrainingBody {
  titulo: string;
  descricao?: string;
  tipo: CreateTrainingBodyTipo;
  modalidade: CreateTrainingBodyModalidade;
  dataRealizacao: string;
  participantes: number;
  status: CreateTrainingBodyStatus;
  responsavel: string;
}

export interface DashboardSummary {
  totalPacientes: number;
  pacientesAtivos: number;
  totalProcessos: number;
  processosEmAndamento: number;
  totalRelatorios: number;
  relatoriosPendentes: number;
  totalTreinamentos: number;
  treinamentosConcluidos: number;
}

export interface DashboardKpis {
  tempoMedioConcessaoDias: number;
  taxaIndeferimento: number;
  totalRetrabalhos: number;
  totalJudicializados: number;
  taxaDeferimento: number;
  relatoriosAprovadosPct: number;
}

export interface StatusCount {
  status: string;
  count: number;
}

export type ListPatientsParams = {
  search?: string;
  status?: ListPatientsStatus;
};

export type ListPatientsStatus =
  (typeof ListPatientsStatus)[keyof typeof ListPatientsStatus];

export const ListPatientsStatus = {
  ativo: "ativo",
  inativo: "inativo",
  em_avaliacao: "em_avaliacao",
} as const;

export type ListReportsParams = {
  patientId?: number;
  status?: ListReportsStatus;
};

export type ListReportsStatus =
  (typeof ListReportsStatus)[keyof typeof ListReportsStatus];

export const ListReportsStatus = {
  rascunho: "rascunho",
  pendente_revisao: "pendente_revisao",
  aprovado: "aprovado",
  enviado_inss: "enviado_inss",
} as const;

export type ListProcessesParams = {
  patientId?: number;
  status?: ListProcessesStatus;
};

export type ListProcessesStatus =
  (typeof ListProcessesStatus)[keyof typeof ListProcessesStatus];

export const ListProcessesStatus = {
  em_andamento: "em_andamento",
  deferido: "deferido",
  indeferido: "indeferido",
  recurso: "recurso",
  judicializado: "judicializado",
} as const;

export type ListRecentProcessesParams = {
  limit?: number;
};
