/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * CAPSLink - Plataforma de integração CAPS e INSS
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Listar pacientes
 */
export const ListPatientsQueryParams = zod.object({
  search: zod.coerce.string().optional(),
  status: zod.enum(["ativo", "inativo", "em_avaliacao"]).optional(),
});

export const ListPatientsResponseItem = zod.object({
  id: zod.number(),
  nome: zod.string(),
  cpf: zod.string(),
  dataNascimento: zod.coerce.date().optional(),
  diagnostico: zod.string().optional(),
  cid: zod.string().optional(),
  status: zod.enum(["ativo", "inativo", "em_avaliacao"]),
  telefone: zod.string().optional(),
  email: zod.string().optional(),
  responsavelTecnico: zod.string().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const ListPatientsResponse = zod.array(ListPatientsResponseItem);

/**
 * @summary Criar paciente
 */
export const CreatePatientBody = zod.object({
  nome: zod.string(),
  cpf: zod.string(),
  dataNascimento: zod.coerce.date().optional(),
  diagnostico: zod.string().optional(),
  cid: zod.string().optional(),
  status: zod.enum(["ativo", "inativo", "em_avaliacao"]),
  telefone: zod.string().optional(),
  email: zod.string().optional(),
  responsavelTecnico: zod.string().optional(),
});

/**
 * @summary Obter paciente por ID
 */
export const GetPatientParams = zod.object({
  id: zod.coerce.number(),
});

export const GetPatientResponse = zod.object({
  id: zod.number(),
  nome: zod.string(),
  cpf: zod.string(),
  dataNascimento: zod.coerce.date().optional(),
  diagnostico: zod.string().optional(),
  cid: zod.string().optional(),
  status: zod.enum(["ativo", "inativo", "em_avaliacao"]),
  telefone: zod.string().optional(),
  email: zod.string().optional(),
  responsavelTecnico: zod.string().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Atualizar paciente
 */
export const UpdatePatientParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdatePatientBody = zod.object({
  nome: zod.string(),
  cpf: zod.string(),
  dataNascimento: zod.coerce.date().optional(),
  diagnostico: zod.string().optional(),
  cid: zod.string().optional(),
  status: zod.enum(["ativo", "inativo", "em_avaliacao"]),
  telefone: zod.string().optional(),
  email: zod.string().optional(),
  responsavelTecnico: zod.string().optional(),
});

export const UpdatePatientResponse = zod.object({
  id: zod.number(),
  nome: zod.string(),
  cpf: zod.string(),
  dataNascimento: zod.coerce.date().optional(),
  diagnostico: zod.string().optional(),
  cid: zod.string().optional(),
  status: zod.enum(["ativo", "inativo", "em_avaliacao"]),
  telefone: zod.string().optional(),
  email: zod.string().optional(),
  responsavelTecnico: zod.string().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Listar relatórios técnicos
 */
export const ListReportsQueryParams = zod.object({
  patientId: zod.coerce.number().optional(),
  status: zod
    .enum(["rascunho", "pendente_revisao", "aprovado", "enviado_inss"])
    .optional(),
});

export const ListReportsResponseItem = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  patientName: zod.string().optional(),
  tipo: zod.enum(["laudo_inicial", "acompanhamento", "pericia", "recurso"]),
  status: zod.enum([
    "rascunho",
    "pendente_revisao",
    "aprovado",
    "enviado_inss",
  ]),
  responsavel: zod.string(),
  conteudo: zod.string().optional(),
  dataEnvio: zod.coerce.date().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const ListReportsResponse = zod.array(ListReportsResponseItem);

/**
 * @summary Criar relatório técnico
 */
export const CreateReportBody = zod.object({
  patientId: zod.number(),
  tipo: zod.enum(["laudo_inicial", "acompanhamento", "pericia", "recurso"]),
  status: zod.enum([
    "rascunho",
    "pendente_revisao",
    "aprovado",
    "enviado_inss",
  ]),
  responsavel: zod.string(),
  conteudo: zod.string().optional(),
  dataEnvio: zod.coerce.date().optional(),
});

/**
 * @summary Obter relatório por ID
 */
export const GetReportParams = zod.object({
  id: zod.coerce.number(),
});

export const GetReportResponse = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  patientName: zod.string().optional(),
  tipo: zod.enum(["laudo_inicial", "acompanhamento", "pericia", "recurso"]),
  status: zod.enum([
    "rascunho",
    "pendente_revisao",
    "aprovado",
    "enviado_inss",
  ]),
  responsavel: zod.string(),
  conteudo: zod.string().optional(),
  dataEnvio: zod.coerce.date().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Atualizar relatório
 */
export const UpdateReportParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateReportBody = zod.object({
  patientId: zod.number(),
  tipo: zod.enum(["laudo_inicial", "acompanhamento", "pericia", "recurso"]),
  status: zod.enum([
    "rascunho",
    "pendente_revisao",
    "aprovado",
    "enviado_inss",
  ]),
  responsavel: zod.string(),
  conteudo: zod.string().optional(),
  dataEnvio: zod.coerce.date().optional(),
});

export const UpdateReportResponse = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  patientName: zod.string().optional(),
  tipo: zod.enum(["laudo_inicial", "acompanhamento", "pericia", "recurso"]),
  status: zod.enum([
    "rascunho",
    "pendente_revisao",
    "aprovado",
    "enviado_inss",
  ]),
  responsavel: zod.string(),
  conteudo: zod.string().optional(),
  dataEnvio: zod.coerce.date().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Excluir relatório
 */
export const DeleteReportParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Listar processos previdenciários
 */
export const ListProcessesQueryParams = zod.object({
  patientId: zod.coerce.number().optional(),
  status: zod
    .enum([
      "em_andamento",
      "deferido",
      "indeferido",
      "recurso",
      "judicializado",
    ])
    .optional(),
});

export const ListProcessesResponseItem = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  patientName: zod.string().optional(),
  numeroProcesso: zod.string(),
  beneficio: zod.enum([
    "bpc_loas",
    "auxilio_doenca",
    "aposentadoria_invalidez",
    "auxilio_acidente",
  ]),
  status: zod.enum([
    "em_andamento",
    "deferido",
    "indeferido",
    "recurso",
    "judicializado",
  ]),
  dataAbertura: zod.coerce.date(),
  dataDecisao: zod.coerce.date().optional(),
  retrabalhos: zod.number(),
  observacoes: zod.string().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const ListProcessesResponse = zod.array(ListProcessesResponseItem);

/**
 * @summary Criar processo previdenciário
 */
export const CreateProcessBody = zod.object({
  patientId: zod.number(),
  numeroProcesso: zod.string(),
  beneficio: zod.enum([
    "bpc_loas",
    "auxilio_doenca",
    "aposentadoria_invalidez",
    "auxilio_acidente",
  ]),
  status: zod.enum([
    "em_andamento",
    "deferido",
    "indeferido",
    "recurso",
    "judicializado",
  ]),
  dataAbertura: zod.coerce.date(),
  dataDecisao: zod.coerce.date().optional(),
  retrabalhos: zod.number().optional(),
  observacoes: zod.string().optional(),
});

/**
 * @summary Obter processo por ID
 */
export const GetProcessParams = zod.object({
  id: zod.coerce.number(),
});

export const GetProcessResponse = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  patientName: zod.string().optional(),
  numeroProcesso: zod.string(),
  beneficio: zod.enum([
    "bpc_loas",
    "auxilio_doenca",
    "aposentadoria_invalidez",
    "auxilio_acidente",
  ]),
  status: zod.enum([
    "em_andamento",
    "deferido",
    "indeferido",
    "recurso",
    "judicializado",
  ]),
  dataAbertura: zod.coerce.date(),
  dataDecisao: zod.coerce.date().optional(),
  retrabalhos: zod.number(),
  observacoes: zod.string().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Atualizar processo
 */
export const UpdateProcessParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateProcessBody = zod.object({
  patientId: zod.number(),
  numeroProcesso: zod.string(),
  beneficio: zod.enum([
    "bpc_loas",
    "auxilio_doenca",
    "aposentadoria_invalidez",
    "auxilio_acidente",
  ]),
  status: zod.enum([
    "em_andamento",
    "deferido",
    "indeferido",
    "recurso",
    "judicializado",
  ]),
  dataAbertura: zod.coerce.date(),
  dataDecisao: zod.coerce.date().optional(),
  retrabalhos: zod.number().optional(),
  observacoes: zod.string().optional(),
});

export const UpdateProcessResponse = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  patientName: zod.string().optional(),
  numeroProcesso: zod.string(),
  beneficio: zod.enum([
    "bpc_loas",
    "auxilio_doenca",
    "aposentadoria_invalidez",
    "auxilio_acidente",
  ]),
  status: zod.enum([
    "em_andamento",
    "deferido",
    "indeferido",
    "recurso",
    "judicializado",
  ]),
  dataAbertura: zod.coerce.date(),
  dataDecisao: zod.coerce.date().optional(),
  retrabalhos: zod.number(),
  observacoes: zod.string().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Processos recentes (feed de atividade)
 */
export const listRecentProcessesQueryLimitDefault = 10;

export const ListRecentProcessesQueryParams = zod.object({
  limit: zod.coerce.number().default(listRecentProcessesQueryLimitDefault),
});

export const ListRecentProcessesResponseItem = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  patientName: zod.string().optional(),
  numeroProcesso: zod.string(),
  beneficio: zod.enum([
    "bpc_loas",
    "auxilio_doenca",
    "aposentadoria_invalidez",
    "auxilio_acidente",
  ]),
  status: zod.enum([
    "em_andamento",
    "deferido",
    "indeferido",
    "recurso",
    "judicializado",
  ]),
  dataAbertura: zod.coerce.date(),
  dataDecisao: zod.coerce.date().optional(),
  retrabalhos: zod.number(),
  observacoes: zod.string().optional(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const ListRecentProcessesResponse = zod.array(
  ListRecentProcessesResponseItem,
);

/**
 * @summary Listar treinamentos
 */
export const ListTrainingsResponseItem = zod.object({
  id: zod.number(),
  titulo: zod.string(),
  descricao: zod.string().optional(),
  tipo: zod.enum(["plataforma", "documentacao", "previdenciario", "outros"]),
  modalidade: zod.enum(["presencial", "online", "hibrido"]),
  dataRealizacao: zod.coerce.date(),
  participantes: zod.number(),
  status: zod.enum(["agendado", "em_andamento", "concluido", "cancelado"]),
  responsavel: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListTrainingsResponse = zod.array(ListTrainingsResponseItem);

/**
 * @summary Criar treinamento
 */
export const CreateTrainingBody = zod.object({
  titulo: zod.string(),
  descricao: zod.string().optional(),
  tipo: zod.enum(["plataforma", "documentacao", "previdenciario", "outros"]),
  modalidade: zod.enum(["presencial", "online", "hibrido"]),
  dataRealizacao: zod.coerce.date(),
  participantes: zod.number(),
  status: zod.enum(["agendado", "em_andamento", "concluido", "cancelado"]),
  responsavel: zod.string(),
});

/**
 * @summary Atualizar treinamento
 */
export const UpdateTrainingParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateTrainingBody = zod.object({
  titulo: zod.string(),
  descricao: zod.string().optional(),
  tipo: zod.enum(["plataforma", "documentacao", "previdenciario", "outros"]),
  modalidade: zod.enum(["presencial", "online", "hibrido"]),
  dataRealizacao: zod.coerce.date(),
  participantes: zod.number(),
  status: zod.enum(["agendado", "em_andamento", "concluido", "cancelado"]),
  responsavel: zod.string(),
});

export const UpdateTrainingResponse = zod.object({
  id: zod.number(),
  titulo: zod.string(),
  descricao: zod.string().optional(),
  tipo: zod.enum(["plataforma", "documentacao", "previdenciario", "outros"]),
  modalidade: zod.enum(["presencial", "online", "hibrido"]),
  dataRealizacao: zod.coerce.date(),
  participantes: zod.number(),
  status: zod.enum(["agendado", "em_andamento", "concluido", "cancelado"]),
  responsavel: zod.string(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Excluir treinamento
 */
export const DeleteTrainingParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Resumo geral do dashboard
 */
export const GetDashboardSummaryResponse = zod.object({
  totalPacientes: zod.number(),
  pacientesAtivos: zod.number(),
  totalProcessos: zod.number(),
  processosEmAndamento: zod.number(),
  totalRelatorios: zod.number(),
  relatoriosPendentes: zod.number(),
  totalTreinamentos: zod.number(),
  treinamentosConcluidos: zod.number(),
});

/**
 * @summary Indicadores de desempenho (KPIs)
 */
export const GetDashboardKpisResponse = zod.object({
  tempoMedioConcessaoDias: zod.number(),
  taxaIndeferimento: zod.number(),
  totalRetrabalhos: zod.number(),
  totalJudicializados: zod.number(),
  taxaDeferimento: zod.number(),
  relatoriosAprovadosPct: zod.number(),
});

/**
 * @summary Distribuição de processos por status
 */
export const GetDashboardProcessStatusResponseItem = zod.object({
  status: zod.string(),
  count: zod.number(),
});
export const GetDashboardProcessStatusResponse = zod.array(
  GetDashboardProcessStatusResponseItem,
);
